argo-cd:
  server:
    replicas: 1
    service:
      type: NodePort
  configs:
    secret:
      createSecret: true
      argocdServerAdminPassword: "$2a$10$K4a5DKnWznR2yRdcvuOEQeIxILUhI/jEUavm8A7zEPHIsv46l.VS2"
  redis-ha:
    enabled: false
  controller:
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicas: 1
